
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: mongoadmin
      password: secret
      database: bullseye

logging:
  level: INFO